apply plugin: 'com.android.application'

android {
    namespace 'com.example.miniapphook'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.miniapphook"
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    compileOnly 'org.lsposed.lsparanoid:lsparanoid:0.6.1'
}